### ISSUE TITLE
Let's use git flow

### ISSUE THREAD

**Issue by wtimme** [snowpunch/AppLove#6]
I'm used to working with _git flow._ What's your opinion on this?

Supporting _git flow_ could be done by
1. creating a new branch `develop`,
2. pushing it to the repo and
3. updating the repository settings and choose `develop` as the main (default) branch

**Comment by snowpunch** [comment]
I'm open to trying it. I'm used to a normal git feature branch workflow. Although at the moment I have a huge refactor (offline because it was experimental at first). I'll commit it in a day or two and then we can use git flow from there if you like. Almost everything has changed (mainly UI, more cocoa-pods added and a side menu with custom IBDesignable menu items etc..) and the code was really cleaned up as well. So yeah, don't waste your time with that old version anymore. I'll have something nice and new for you in a couple days. Then we can proceed from there with git flow.

**Comment by snowpunch** [comment]
The new version also has better support for iPad and iPhone 6+ with UISplitView and collapsable views. Plus other things as well. I think you will like it.
